#!/usr/bin/ruby
# vim: filetype=ruby
#
# Check file descriptor usage reading /proc/sys/fs/file-nr
# Check proc(5) manpage
#

PLUGIN_VERSION = "1.0"

used = 0
free = 0
max = 0
File.open('/proc/sys/fs/file-nr') do |f|
  used, free, max = f.gets.chomp.strip.split
end

perfdata = "used=#{used} max=#{max}"
usage = (used.to_i*100.0)/max.to_i
if ARGV.include?("-v") or ARGV.include?("--version")
  puts "check_file_descriptors version #{PLUGIN_VERSION}"
else
  puts "File descriptors usage #{perfdata} (#{usage.round}% aprox.) | #{perfdata}"
end

if usage > 70
  exit 1
elsif usage > 90
  exit 2
else
  exit 0
end


